//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.SoE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.SoE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard! ähnelt.
        /// </summary>
        public static string AlertCopiedToClipboard {
            get {
                return ResourceManager.GetString("AlertCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download file &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string AlertDownloadConfirmationFileTemplate {
            get {
                return ResourceManager.GetString("AlertDownloadConfirmationFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to clipboard ähnelt.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string ButtonDownloadFile {
            get {
                return ResourceManager.GetString("ButtonDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get value ähnelt.
        /// </summary>
        public static string ButtonGetValue {
            get {
                return ResourceManager.GetString("ButtonGetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide localization ähnelt.
        /// </summary>
        public static string ButtonHideLocalization {
            get {
                return ResourceManager.GetString("ButtonHideLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string ButtonOff {
            get {
                return ResourceManager.GetString("ButtonOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string ButtonOn {
            get {
                return ResourceManager.GetString("ButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set value ähnelt.
        /// </summary>
        public static string ButtonSetValue {
            get {
                return ResourceManager.GetString("ButtonSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show localization ähnelt.
        /// </summary>
        public static string ButtonShowLocalization {
            get {
                return ResourceManager.GetString("ButtonShowLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare SRAM files ähnelt.
        /// </summary>
        public static string ButtonTitleCompare {
            get {
                return ResourceManager.GetString("ButtonTitleCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy text to clipboard ähnelt.
        /// </summary>
        public static string ButtonTitleCopy {
            get {
                return ResourceManager.GetString("ButtonTitleCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy localization to clipboard ähnelt.
        /// </summary>
        public static string ButtonTitleCopyLocalization {
            get {
                return ResourceManager.GetString("ButtonTitleCopyLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable auto-translate ähnelt.
        /// </summary>
        public static string ButtonTitleDisableAutoTranslation {
            get {
                return ResourceManager.GetString("ButtonTitleDisableAutoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download changed file ähnelt.
        /// </summary>
        public static string ButtonTitleDownloadChangedFile {
            get {
                return ResourceManager.GetString("ButtonTitleDownloadChangedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download as text file ähnelt.
        /// </summary>
        public static string ButtonTitleDownloadFile {
            get {
                return ResourceManager.GetString("ButtonTitleDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable auto-translate ähnelt.
        /// </summary>
        public static string ButtonTitleEnableAutoTranslation {
            get {
                return ResourceManager.GetString("ButtonTitleEnableAutoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get offset value ähnelt.
        /// </summary>
        public static string ButtonTitleGetOffsetValue {
            get {
                return ResourceManager.GetString("ButtonTitleGetOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set offset value ähnelt.
        /// </summary>
        public static string ButtonTitleSetOffsetValue {
            get {
                return ResourceManager.GetString("ButtonTitleSetOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM - Web Compare ähnelt.
        /// </summary>
        public static string CaptionWebCompare {
            get {
                return ResourceManager.GetString("CaptionWebCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM - Web Offset Edit ähnelt.
        /// </summary>
        public static string CaptionWebOffsetEdit {
            get {
                return ResourceManager.GetString("CaptionWebOffsetEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All save slots ähnelt.
        /// </summary>
        public static string EnumAllSaveSlots {
            get {
                return ResourceManager.GetString("EnumAllSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compared save slots ähnelt.
        /// </summary>
        public static string EnumComparedSaveSlots {
            get {
                return ResourceManager.GetString("EnumComparedSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compared save slots if different ähnelt.
        /// </summary>
        public static string EnumComparedSaveSlotsIfDifferent {
            get {
                return ResourceManager.GetString("EnumComparedSaveSlotsIfDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t show ähnelt.
        /// </summary>
        public static string EnumDontShow {
            get {
                return ResourceManager.GetString("EnumDontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #1 ähnelt.
        /// </summary>
        public static string EnumSaveSlot1 {
            get {
                return ResourceManager.GetString("EnumSaveSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #1 only ähnelt.
        /// </summary>
        public static string EnumSaveSlot1Only {
            get {
                return ResourceManager.GetString("EnumSaveSlot1Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #2 ähnelt.
        /// </summary>
        public static string EnumSaveSlot2 {
            get {
                return ResourceManager.GetString("EnumSaveSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #2 only ähnelt.
        /// </summary>
        public static string EnumSaveSlot2Only {
            get {
                return ResourceManager.GetString("EnumSaveSlot2Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #3 ähnelt.
        /// </summary>
        public static string EnumSaveSlot3 {
            get {
                return ResourceManager.GetString("EnumSaveSlot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #3 only ähnelt.
        /// </summary>
        public static string EnumSaveSlot3Only {
            get {
                return ResourceManager.GetString("EnumSaveSlot3Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #4 ähnelt.
        /// </summary>
        public static string EnumSaveSlot4 {
            get {
                return ResourceManager.GetString("EnumSaveSlot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #4 only ähnelt.
        /// </summary>
        public static string EnumSaveSlot4Only {
            get {
                return ResourceManager.GetString("EnumSaveSlot4Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: File has wrong file extension
        /// ähnelt.
        /// </summary>
        public static string ErrorWrongFileExtensionTemplate {
            get {
                return ResourceManager.GetString("ErrorWrongFileExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional comparisons ähnelt.
        /// </summary>
        public static string LabelAdditionalComparisons {
            get {
                return ResourceManager.GetString("LabelAdditionalComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string LabelAppVersion {
            get {
                return ResourceManager.GetString("LabelAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto translate ähnelt.
        /// </summary>
        public static string LabelAutoTranslate {
            get {
                return ResourceManager.GetString("LabelAutoTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string LabelChangeLog {
            get {
                return ResourceManager.GetString("LabelChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colorize output ähnelt.
        /// </summary>
        public static string LabelColorizeOutput {
            get {
                return ResourceManager.GetString("LabelColorizeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string LabelFile {
            get {
                return ResourceManager.GetString("LabelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die known bytes ähnelt.
        /// </summary>
        public static string LabelKnownBytes {
            get {
                return ResourceManager.GetString("LabelKnownBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link opens in a new tab ähnelt.
        /// </summary>
        public static string LabelLinkOpensInNewTab {
            get {
                return ResourceManager.GetString("LabelLinkOpensInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mandatory ähnelt.
        /// </summary>
        public static string LabelMandatory {
            get {
                return ResourceManager.GetString("LabelMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset value ähnelt.
        /// </summary>
        public static string LabelOffsetValue {
            get {
                return ResourceManager.GetString("LabelOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show additional save slot information ähnelt.
        /// </summary>
        public static string LabelShowAdditionalSaveSlotInformation {
            get {
                return ResourceManager.GetString("LabelShowAdditionalSaveSlotInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select either a SRAM (*.srm) or Snes9x savestate file (*.000 - *.009; *.state) ähnelt.
        /// </summary>
        public static string LabelTitleFile {
            get {
                return ResourceManager.GetString("LabelTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare non-save slot area byte by byte (area beyond all save slots) ähnelt.
        /// </summary>
        public static string LabelTitleNonSaveSlotByteByByteComparison {
            get {
                return ResourceManager.GetString("LabelTitleNonSaveSlotByteByByteComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format Exploration Project ähnelt.
        /// </summary>
        public static string LabelTitleProjectName {
            get {
                return ResourceManager.GetString("LabelTitleProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format exploration status ähnelt.
        /// </summary>
        public static string LabelTitleProjectStatus {
            get {
                return ResourceManager.GetString("LabelTitleProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare whole save slot area byte by byte (including the &quot;knowns&quot; areas) ähnelt.
        /// </summary>
        public static string LabelTitleSaveSlotByteByByteComparison {
            get {
                return ResourceManager.GetString("LabelTitleSaveSlotByteByByteComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The relative offset within the gameslot area ähnelt.
        /// </summary>
        public static string LabelTitleSaveSlotOffset {
            get {
                return ResourceManager.GetString("LabelTitleSaveSlotOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This value changes at every in-game save - maybe a timestamp or similar ähnelt.
        /// </summary>
        public static string LabelTitleUnknown12B {
            get {
                return ResourceManager.GetString("LabelTitleUnknown12B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unknown bytes ähnelt.
        /// </summary>
        public static string LabelUnknownBytes {
            get {
                return ResourceManager.GetString("LabelUnknownBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the Evermore Format Exploration Project! ähnelt.
        /// </summary>
        public static string LabelWelcomeMessage {
            get {
                return ResourceManager.GetString("LabelWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Awesome SoE ähnelt.
        /// </summary>
        public static string MenuAwesomeSoE {
            get {
                return ResourceManager.GetString("MenuAwesomeSoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string MenuChangeLog {
            get {
                return ResourceManager.GetString("MenuChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Community ähnelt.
        /// </summary>
        public static string MenuCommunity {
            get {
                return ResourceManager.GetString("MenuCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can I help? ähnelt.
        /// </summary>
        public static string MenuContribute {
            get {
                return ResourceManager.GetString("MenuContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exploring SRAM ähnelt.
        /// </summary>
        public static string MenuExplore {
            get {
                return ResourceManager.GetString("MenuExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Features ähnelt.
        /// </summary>
        public static string MenuFeatures {
            get {
                return ResourceManager.GetString("MenuFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goals of this Project ähnelt.
        /// </summary>
        public static string MenuGoals {
            get {
                return ResourceManager.GetString("MenuGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guide (SRM) ähnelt.
        /// </summary>
        public static string MenuGuide {
            get {
                return ResourceManager.GetString("MenuGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guide (Savestate) ähnelt.
        /// </summary>
        public static string MenuGuideSavestate {
            get {
                return ResourceManager.GetString("MenuGuideSavestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string MenuHistory {
            get {
                return ResourceManager.GetString("MenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images ähnelt.
        /// </summary>
        public static string MenuImagery {
            get {
                return ResourceManager.GetString("MenuImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick links ähnelt.
        /// </summary>
        public static string MenuQuickLinks {
            get {
                return ResourceManager.GetString("MenuQuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console App ähnelt.
        /// </summary>
        public static string MenuSramComparerCmdApp {
            get {
                return ResourceManager.GetString("MenuSramComparerCmdApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM Comparison ähnelt.
        /// </summary>
        public static string MenuSramComparison {
            get {
                return ResourceManager.GetString("MenuSramComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentation ähnelt.
        /// </summary>
        public static string MenuSramDocu {
            get {
                return ResourceManager.GetString("MenuSramDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM Format ähnelt.
        /// </summary>
        public static string MenuSramFormat {
            get {
                return ResourceManager.GetString("MenuSramFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Unknowns ähnelt.
        /// </summary>
        public static string MenuTheUnknowns {
            get {
                return ResourceManager.GetString("MenuTheUnknowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version infos and contributors ähnelt.
        /// </summary>
        public static string MenuTitleAbout {
            get {
                return ResourceManager.GetString("MenuTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Awesome pages for an awesome game ähnelt.
        /// </summary>
        public static string MenuTitleAwesome {
            get {
                return ResourceManager.GetString("MenuTitleAwesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console App changelog and downloads ähnelt.
        /// </summary>
        public static string MenuTitleChangeLog {
            get {
                return ResourceManager.GetString("MenuTitleChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Community (Discord, Forum, etc.) ähnelt.
        /// </summary>
        public static string MenuTitleCommunity {
            get {
                return ResourceManager.GetString("MenuTitleCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web compare of SRAM files ähnelt.
        /// </summary>
        public static string MenuTitleCompare {
            get {
                return ResourceManager.GetString("MenuTitleCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How to contribute to the project ähnelt.
        /// </summary>
        public static string MenuTitleContribute {
            get {
                return ResourceManager.GetString("MenuTitleContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Discord invite ähnelt.
        /// </summary>
        public static string MenuTitleDiscord {
            get {
                return ResourceManager.GetString("MenuTitleDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How to explore the SRAM ähnelt.
        /// </summary>
        public static string MenuTitleExploring {
            get {
                return ResourceManager.GetString("MenuTitleExploring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Features of SRAM-Comparer ähnelt.
        /// </summary>
        public static string MenuTitleFeatures {
            get {
                return ResourceManager.GetString("MenuTitleFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The goals of this project ähnelt.
        /// </summary>
        public static string MenuTitleGoals {
            get {
                return ResourceManager.GetString("MenuTitleGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console App Guide (SRM) ähnelt.
        /// </summary>
        public static string MenuTitleGuide {
            get {
                return ResourceManager.GetString("MenuTitleGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console App Guide (Savestate) ähnelt.
        /// </summary>
        public static string MenuTitleGuideSavestate {
            get {
                return ResourceManager.GetString("MenuTitleGuideSavestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console App Imagery ähnelt.
        /// </summary>
        public static string MenuTitleImagery {
            get {
                return ResourceManager.GetString("MenuTitleImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web offset edit ähnelt.
        /// </summary>
        public static string MenuTitleOffsetEdit {
            get {
                return ResourceManager.GetString("MenuTitleOffsetEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sources at GitHub ähnelt.
        /// </summary>
        public static string MenuTitleSources {
            get {
                return ResourceManager.GetString("MenuTitleSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM Documentation ähnelt.
        /// </summary>
        public static string MenuTitleSramDocu {
            get {
                return ResourceManager.GetString("MenuTitleSramDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What are the Unknowns to explore? ähnelt.
        /// </summary>
        public static string MenuTitleTheUnknowns {
            get {
                return ResourceManager.GetString("MenuTitleTheUnknowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare ähnelt.
        /// </summary>
        public static string MenuWebComparison {
            get {
                return ResourceManager.GetString("MenuWebComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset Edit ähnelt.
        /// </summary>
        public static string MenuWebOffsetEdit {
            get {
                return ResourceManager.GetString("MenuWebOffsetEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web Tools ähnelt.
        /// </summary>
        public static string MenuWebTools {
            get {
                return ResourceManager.GetString("MenuWebTools", resourceCulture);
            }
        }
    }
}
