//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SramComparer.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SramComparer.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional comparisons ähnelt.
        /// </summary>
        public static string AdditionalComparisons {
            get {
                return ResourceManager.GetString("AdditionalComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Affected games only ähnelt.
        /// </summary>
        public static string AffectedGamesOnly {
            get {
                return ResourceManager.GetString("AffectedGamesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All games ähnelt.
        /// </summary>
        public static string AllGames {
            get {
                return ResourceManager.GetString("AllGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compiled at ähnelt.
        /// </summary>
        public static string AppCompiledAt {
            get {
                return ResourceManager.GetString("AppCompiledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Awesome SoE ähnelt.
        /// </summary>
        public static string AwesomeSoE {
            get {
                return ResourceManager.GetString("AwesomeSoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to clipboard ähnelt.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string ButtonDownloadFile {
            get {
                return ResourceManager.GetString("ButtonDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get value ähnelt.
        /// </summary>
        public static string ButtonGetValue {
            get {
                return ResourceManager.GetString("ButtonGetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set value ähnelt.
        /// </summary>
        public static string ButtonSetValue {
            get {
                return ResourceManager.GetString("ButtonSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksum ähnelt.
        /// </summary>
        public static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comparison SRAM-File ähnelt.
        /// </summary>
        public static string ComparisonSramFile {
            get {
                return ResourceManager.GetString("ComparisonSramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current SRAM-File ähnelt.
        /// </summary>
        public static string CurrentSramFile {
            get {
                return ResourceManager.GetString("CurrentSramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t show ähnelt.
        /// </summary>
        public static string DontShow {
            get {
                return ResourceManager.GetString("DontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download file &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string DownloadConfirmationFileTemplate {
            get {
                return ResourceManager.GetString("DownloadConfirmationFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Features ähnelt.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File region ähnelt.
        /// </summary>
        public static string FileRegion {
            get {
                return ResourceManager.GetString("FileRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forums ähnelt.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To share your opinions or findings consider posting at the forums. Your community help is appreciated! ähnelt.
        /// </summary>
        public static string ForumsTitle {
            get {
                return ResourceManager.GetString("ForumsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game ähnelt.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #1 ähnelt.
        /// </summary>
        public static string Game1 {
            get {
                return ResourceManager.GetString("Game1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #1 only ähnelt.
        /// </summary>
        public static string Game1Only {
            get {
                return ResourceManager.GetString("Game1Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #2 ähnelt.
        /// </summary>
        public static string Game2 {
            get {
                return ResourceManager.GetString("Game2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #2 only ähnelt.
        /// </summary>
        public static string Game2Only {
            get {
                return ResourceManager.GetString("Game2Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #3 ähnelt.
        /// </summary>
        public static string Game3 {
            get {
                return ResourceManager.GetString("Game3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #3 only ähnelt.
        /// </summary>
        public static string Game3Only {
            get {
                return ResourceManager.GetString("Game3Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #4 ähnelt.
        /// </summary>
        public static string Game4 {
            get {
                return ResourceManager.GetString("Game4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #4 only ähnelt.
        /// </summary>
        public static string Game4Only {
            get {
                return ResourceManager.GetString("Game4Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download changed file ähnelt.
        /// </summary>
        public static string HintButtonDownloadChangedFile {
            get {
                return ResourceManager.GetString("HintButtonDownloadChangedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get offset value ähnelt.
        /// </summary>
        public static string HintButtonGetOffsetValue {
            get {
                return ResourceManager.GetString("HintButtonGetOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set offset value ähnelt.
        /// </summary>
        public static string HintButtonSetOffsetValue {
            get {
                return ResourceManager.GetString("HintButtonSetOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare the files ähnelt.
        /// </summary>
        public static string HintCompare {
            get {
                return ResourceManager.GetString("HintCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy text to clipboard ähnelt.
        /// </summary>
        public static string HintCopyButton {
            get {
                return ResourceManager.GetString("HintCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download as text file ähnelt.
        /// </summary>
        public static string HintDownloadFile {
            get {
                return ResourceManager.GetString("HintDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show changelog ähnelt.
        /// </summary>
        public static string HintShowChangelog {
            get {
                return ResourceManager.GetString("HintShowChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How can I help? ähnelt.
        /// </summary>
        public static string HowCanIHelp {
            get {
                return ResourceManager.GetString("HowCanIHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How to use? ähnelt.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I wanna see images! ähnelt.
        /// </summary>
        public static string Imagery {
            get {
                return ResourceManager.GetString("Imagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link opens in a new tab ähnelt.
        /// </summary>
        public static string LinkOpensInNewTab {
            get {
                return ResourceManager.GetString("LinkOpensInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mandatory ähnelt.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard! ähnelt.
        /// </summary>
        public static string MessageCopiedToClipboard {
            get {
                return ResourceManager.GetString("MessageCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non game buffer ähnelt.
        /// </summary>
        public static string NonGameBuffer {
            get {
                return ResourceManager.GetString("NonGameBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comparison of non game buffer (after all game sections) ähnelt.
        /// </summary>
        public static string NonGameBufferHint {
            get {
                return ResourceManager.GetString("NonGameBufferHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset value ähnelt.
        /// </summary>
        public static string OffsetValue {
            get {
                return ResourceManager.GetString("OffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The source code is hosted at  ähnelt.
        /// </summary>
        public static string OpenSourceHistTitleFragment {
            get {
                return ResourceManager.GetString("OpenSourceHistTitleFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pages ähnelt.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prerequisites ähnelt.
        /// </summary>
        public static string Prerequisites {
            get {
                return ResourceManager.GetString("Prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Me ähnelt.
        /// </summary>
        public static string ReadMe {
            get {
                return ResourceManager.GetString("ReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show additional game information ähnelt.
        /// </summary>
        public static string ShowAdditionalGameInformation {
            get {
                return ResourceManager.GetString("ShowAdditionalGameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM - Comparer ähnelt.
        /// </summary>
        public static string SramComparer {
            get {
                return ResourceManager.GetString("SramComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM - Comparer (and everything else here) is open-source! ähnelt.
        /// </summary>
        public static string SramComparerOpenSourceDisclaimer {
            get {
                return ResourceManager.GetString("SramComparerOpenSourceDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM Documentation ähnelt.
        /// </summary>
        public static string SramDocumentation {
            get {
                return ResourceManager.GetString("SramDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM-File ähnelt.
        /// </summary>
        public static string SramFile {
            get {
                return ResourceManager.GetString("SramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM - Offset Edit ähnelt.
        /// </summary>
        public static string SramOffsetEdit {
            get {
                return ResourceManager.GetString("SramOffsetEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRAM - Tools ähnelt.
        /// </summary>
        public static string SramTools {
            get {
                return ResourceManager.GetString("SramTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Unknowns ähnelt.
        /// </summary>
        public static string TheUnknowns {
            get {
                return ResourceManager.GetString("TheUnknowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Awesome pages for an awesome game ähnelt.
        /// </summary>
        public static string TooltipAwesomeSoE {
            get {
                return ResourceManager.GetString("TooltipAwesomeSoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown12B ähnelt.
        /// </summary>
        public static string Unknown12B {
            get {
                return ResourceManager.GetString("Unknown12B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This value changes at every in-game save - maybe a timestamp or similar ähnelt.
        /// </summary>
        public static string Unknown12BHint {
            get {
                return ResourceManager.GetString("Unknown12BHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use colored output ähnelt.
        /// </summary>
        public static string UseColoredOutput {
            get {
                return ResourceManager.GetString("UseColoredOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web Compare SRAM ähnelt.
        /// </summary>
        public static string WebComparison {
            get {
                return ResourceManager.GetString("WebComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web Offset Edit ähnelt.
        /// </summary>
        public static string WebOffset {
            get {
                return ResourceManager.GetString("WebOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web - Tools ähnelt.
        /// </summary>
        public static string WebTools {
            get {
                return ResourceManager.GetString("WebTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What&apos;s unknown? ähnelt.
        /// </summary>
        public static string WhatIsUnknown {
            get {
                return ResourceManager.GetString("WhatIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whole game buffer ähnelt.
        /// </summary>
        public static string WholeGameBuffer {
            get {
                return ResourceManager.GetString("WholeGameBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comparison of whole game buffer (including the &quot;knowns&quot;) ähnelt.
        /// </summary>
        public static string WholeGameBufferHint {
            get {
                return ResourceManager.GetString("WholeGameBufferHint", resourceCulture);
            }
        }
    }
}
